### ISSUE TITLE
the command line has error related to libva

### ISSUE THREAD

**Issue by feitian124** [cawa-93/vite-electron-builder#270]
the command line has error related to libva, but vite-electron-builder seems work still, 

**Describe the bug**
```shell
 2021-05-17 16:21:28 ⌚  ming-manjaro in ~/learn/js/vite-electron-builder
± |main U:1 ✗| → npm run watch

> watch
> node scripts/watch.js

下午4:21:36 [main] libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

下午4:21:36 [main] Failed install extension: Error: Version of Electron: 12.0.7 does not match required range >=1.2.1 for extension ljjemllljcmogpfapbkkighbhhppjdbg
    at install (/home/ming/learn/js/vite-electron-builder/packages/main/dist/index.js:7873:29)
    at /home/ming/learn/js/vite-electron-builder/packages/main/dist/index.cjs:52:100

```

**To Reproduce**
1. git clone 
2. npm run watch

**Expected behavior**
no errors

**Additional context**
my env:

```shell
Lib versions
node: v14.16.0
v8: v8.9.255.25-electron.0
uv: v1.40.0
zlib: v1.2.11
brotli: v1.0.9
ares: v1.16.1
modules: v87
nghttp2: v1.41.0
napi: v7
llhttp: v2.1.3
openssl: v1.1.1
icu: v68.1
unicode: v13.0
electron: v12.0.7
chrome: v89.0.4389.128
```

```shell
 2021-05-17 16:26:00 ⌚  ming-manjaro in ~/learn/js/vite-electron-builder
± |main U:1 ✗| → node -v
v14.17.0

 2021-05-17 16:26:10 ⌚  ming-manjaro in ~/learn/js/vite-electron-builder
± |main U:1 ✗| → npm -v
7.13.0

 2021-05-17 16:26:18 ⌚  ming-manjaro in ~/learn/js/vite-electron-builder
± |main U:1 ✗| → screenfetch 

 ██████████████████  ████████     ming@ming-manjaro
 ██████████████████  ████████     OS: Manjaro 21.0.3 Ornara
 ██████████████████  ████████     Kernel: x86_64 Linux 5.9.16-1-MANJARO
 ██████████████████  ████████     Uptime: 9h 13m
 ████████            ████████     Packages: 1228
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.81.0 / Plasma 5.21.4
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breath2
 ████████  ████████  ████████     Disk: 92G / 114G (85%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics @ 12x 1.697GHz
 ████████  ████████  ████████     GPU: SVGA3D; build
                                  RAM: 7640408064-

 2021-05-17 16:26:23 ⌚  ming-manjaro in ~/learn/js/vite-electron-builder
```

**Comment by cawa-93** [comment]
I do not think that the problem with libva is somehow associated with this template. Perhaps this bug with an electron or something else. In any case, I have no opportunity to protest it in manjaro system.

I will leave this issues opened. If you find a solution - write it here.

**Comment by cawa-93** [comment]
As for this message:
```node
下午4:21:36 [main] Failed install extension: Error: Version of Electron: 12.0.7 does not match required range >=1.2.1 for extension ljjemllljcmogpfapbkkighbhhppjdbg
    at install (/home/ming/learn/js/vite-electron-builder/packages/main/dist/index.js:7873:29)
    at /home/ming/learn/js/vite-electron-builder/packages/main/dist/index.cjs:52:100
```

It should be fixed by https://github.com/cawa-93/vite-electron-builder/commit/f20a11428e9071ac5eefb3605fefafb525674b2c

**Comment by feitian124** [comment]
thanks. 
i am freshman to electron,  my manjaro is acatually a virtual machine in vmware, not sure if this is the reason. someone said they meet similiar issue about libva in VM.

**Comment by feitian124** [comment]
https://github.com/intel/libva/issues/278
paste here for tracking,  i am also amd cpu in vmware, manjaro
