### ISSUE TITLE
Release for ubuntu fails due to snapcraft is not installed

### ISSUE THREAD

**Issue by ste163** [cawa-93/vite-electron-builder#471]
**Describe the bug**
First, I just want to say thank you so much for this fantastic template! I was using the Vue CLI Plugin Electron Builder, but it's not as up-to-date or as awesome as Vite, and this template made converting to Vite a breeze.

Now for the issue: the only change I made to the release.yml was as per the comment:
```
    #    To compile the application for different platforms, use:
    #    os: [ macos-latest, ubuntu-latest, windows-latest ]
```
I made that change as I'm wanting to release for all platforms, and now the release fails for ubuntu-latest. It still creates the app image perfectly, but crashes at the snap store. (I believe you can check the failed action here: https://github.com/ste163/vislit/runs/3794128439?check_suite_focus=true)

**To Reproduce**
1. Change your release.yml's OS line 87 to `[ macos-latest, ubuntu-latest, windows-latest ]`
2. Push to main
3. Ubuntu should fail due snapcraft not being installed. Mac and Windows should build just fine

**Expected behavior**
The release should build for the snap store; however, I don't really need it. I'm good with just having the app image.

**Screenshots**
Error message:
```
Error: Command failed: npx --no-install electron-builder --linux --publish always --config electron-builder.config.js
  • electron-builder  version=22.11.7 os=5.8.0-1042-azure
  • loaded configuration  file=/home/runner/work/vislit/vislit/electron-builder.config.js
  • description is missed in the package.json  appPackageFile=/home/runner/work/vislit/vislit/package.json
  • author is missed in the package.json  appPackageFile=/home/runner/work/vislit/vislit/package.json
  • packaging       platform=linux arch=x64 electron=15.1.0 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/vislit_21.10.4-1033_amd64.snap
  • building        target=AppImage arch=x64 file=dist/vislit-21.10.4-1033.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • publishing      publisher=Github (owner: ste163, project: vislit, version: 21.10.4-1033)
  • uploading       file=vislit-21.10.4-1033.AppImage provider=GitHub
  • overwrite published file  file=vislit-21.10.4-1033.AppImage reason=already exists on GitHub
  • publishing      publisher=Snap Store
  • uploading       file=vislit_21.10.4-1033_amd64.snap provider=snapStore
  ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  
  ⨯ /home/runner/work/vislit/vislit/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /home/runner/work/vislit/vislit/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/home/runner/work/vislit/vislit/node_modules/builder-util/src/util.ts:249:14)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
				^

Error: Command failed: npx --no-install electron-builder --linux --publish always --config electron-builder.config.js
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:132:4)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2006,
  stdout: null,
  stderr: null
}
```

**Comment by cawa-93** [comment]
As in logs says:
```
snapcraft is not installed, please: sudo snap install snapcraft --classic  
```

Maybe you should add 1 extra step for Ubuntu before build. If you find cool solution -- PR are welcome.

**Comment by ste163** [comment]
I'll try that! I'm new to github actions, so I didn't know if that was something that would actually work

**Comment by ste163** [comment]
Added the following right after the `actions/setup-node@v2`, which installs snapcraft successfully, but now there's another issue related to snapcraft/`samuelmeuli/action-electron-builder/v1`.

Working if check:
```
      - name: Install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo snap install snapcraft --classic
```


I read over the `action-electron-builder`, but couldn't tell if there's a way to configure it to not target snap? I'm not trying to get my super early version of my app actually onto any app stores right now, which appears to be what the action is trying to do. It's erroring out because I'm not sending any authorization to the snap store

Error:
~~~
Attempt 2 failed:

Error: Command failed: npx --no-install electron-builder --linux --publish always --config electron-builder.config.js
  • electron-builder  version=22.11.7 os=5.8.0-1042-azure
  • loaded configuration  file=/home/runner/work/vislit/vislit/electron-builder.config.js
  • description is missed in the package.json  appPackageFile=/home/runner/work/vislit/vislit/package.json
  • author is missed in the package.json  appPackageFile=/home/runner/work/vislit/vislit/package.json
  • packaging       platform=linux arch=x64 electron=15.1.0 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/vislit_21.10.4-1269_amd64.snap
  • building        target=AppImage arch=x64 file=dist/vislit-21.10.4-1269.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • publishing      publisher=Github (owner: ste163, project: vislit, version: 21.10.4-1269)
  • uploading       file=vislit-21.10.4-1269.AppImage provider=GitHub
  • overwrite published file  file=vislit-21.10.4-1269.AppImage reason=already exists on GitHub
  • publishing      publisher=Snap Store
  • uploading       file=vislit_21.10.4-1269_amd64.snap provider=snapStore
DEPRECATED: The 'push' set of commands have been replaced with 'upload'.
See http://snapcraft.io/docs/deprecation-notices/dn11 for more information.
Preparing to upload 'vislit_21.10.4-1269_amd64.snap'.
After uploading, the resulting snap revision will be released to 'edge' when it passes the Snap Store review.
Install the review-tools from the Snap Store for enhanced checks before uploading this snap.
Received:
- macaroon-authorization-required: The request is missing an Authorization header field containing a valid macaroon
  ⨯ exit status 2
github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr
	/Volumes/data/Documents/app-builder/pkg/util/exec.go:23
github.com/develar/app-builder/pkg/package-format/snap.publishToStore
	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:35
github.com/develar/app-builder/pkg/package-format/snap.ConfigurePublishCommand.func1
	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:18
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:90
runtime.main
	/usr/local/Cellar/go/1.16/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:1371  
  ⨯ /home/runner/work/vislit/vislit/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /home/runner/work/vislit/vislit/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/home/runner/work/vislit/vislit/node_modules/builder-util/src/util.ts:249:14)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
				^

Error: Command failed: npx --no-install electron-builder --linux --publish always --config electron-builder.config.js
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:132:4)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2263,
  stdout: null,
  stderr: null
}
~~~

**Comment by cawa-93** [comment]
action-electron-builder has `release` param to avoid publishing. For more you may want create question there. 
Also electron-builder has [`target`](https://www.electron.build/configuration/linux) option to change package type.

**Comment by ste163** [comment]
Awesome, will check those out! Thanks!

**Comment by ste163** [comment]
Adding the following to `electron-builder.config.js` 'fixed' the issue as it no longer targets snap:
```
linux: {
  target: "AppImage"
}
```
When I get to the point where my app is ready for release, I'll check into get snap working.

Thanks for all your help!
