### ISSUE TITLE
yarn watch and npm watch got error with node v17.5.0 and node v16.12.0

### ISSUE THREAD

**Issue by yingshaoxo** [cawa-93/vite-electron-builder#779]
```bash
(base) yingshaoxo@macos library % yarn watch                       
yarn run v1.22.17
$ node scripts/watch.js
Pre-bundling dependencies:
  vue
  element-plus
  ipfs-core
(this will be run only when your dependencies or config have changed)
✘ [ERROR] No matching export in "browser-external:url" for import "parse"

    node_modules/electron-fetch/lib/index.es.js:1:9:
      1 │ import { parse, format, resolve } from 'url';
        ╵          ~~~~~

✘ [ERROR] No matching export in "browser-external:url" for import "format"

    node_modules/electron-fetch/lib/index.es.js:1:16:
      1 │ import { parse, format, resolve } from 'url';
        ╵                 ~~~~~~

✘ [ERROR] No matching export in "browser-external:url" for import "resolve"

    node_modules/electron-fetch/lib/index.es.js:1:24:
      1 │ import { parse, format, resolve } from 'url';
        ╵                         ~~~~~~~

✘ [ERROR] No matching export in "browser-external:http" for import "STATUS_CODES"

    node_modules/electron-fetch/lib/index.es.js:3:9:
      3 │ import { STATUS_CODES } from 'http';
        ╵          ~~~~~~~~~~~~

✘ [ERROR] No matching export in "browser-external:stream" for import "PassThrough"

    node_modules/electron-fetch/lib/index.es.js:6:17:
      6 │ import Stream, { PassThrough } from 'stream';
        ╵                  ~~~~~~~~~~~

Error: Build failed with 5 errors:
node_modules/electron-fetch/lib/index.es.js:1:9: ERROR: No matching export in "browser-external:url" for import "parse"
node_modules/electron-fetch/lib/index.es.js:1:16: ERROR: No matching export in "browser-external:url" for import "format"
node_modules/electron-fetch/lib/index.es.js:1:24: ERROR: No matching export in "browser-external:url" for import "resolve"
node_modules/electron-fetch/lib/index.es.js:3:9: ERROR: No matching export in "browser-external:http" for import "STATUS_CODES"
node_modules/electron-fetch/lib/index.es.js:6:17: ERROR: No matching export in "browser-external:stream" for import "PassThrough"
    at failureErrorWithLog (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1602:15)
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1248:28
    at runOnEndCallbacks (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1033:63)
    at buildResponseToResult (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1246:7)
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1355:14
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:665:9
    at handleIncomingPacket (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "parse"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "format"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "resolve"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:http" for import "STATUS_CODES"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:stream" for import "PassThrough"'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yingshaoxo** [comment]
Got it, it's because of using `ipfs-core` in the rendering script.

I don't know why there has no error message that tells me it's a rendering script error.
